application:
  server:
    port: 8080
spring:
  application:
    name: Kinect
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    username: username
    password: password
    url: jdbc:h2:mem:kinectdb
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  security:
    user:
      name: username
      password: password
  mail:
    host: smtp.gmail.com
    port: 587
    username: gym.buddies.mobile@gmail.com
    password: gymbuddies123@
