server:
  port: 8080

spring:
  application:
    name: Kinect
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: root
    url: jdbc:mysql://localhost/kinectdb?autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
